# Change these first
owner: StarCitizenTools # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Main wiki
    url: https://starcitizen.tools
  - name: Development wiki
    url: https://dev.starcitizen.tools/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://starcitizen.tools/resources/assets/sitelogo.svg
  name: Star Citizen Tools
  introTitle:
  introMessage:
  navbar:
    - title: Wiki
      href: https://starcitizen.tools
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
