# Change these first
owner: StarCitizenTools # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Wiki
    url: https://starcitizen.tools
  - name: Action API
    url: https://starcitizen.tools/api.php?action=query&prop=info&titles=Gladius
    method: GET
  - name: Parsoid
    url: https://starcitizen.tools/api.php?action=visualeditor&format=json&paction=parse&page=Star_Citizen_Wiki
    method: GET
    __dangerous__body_down: "apierror-"
  #- name: REST API (main wiki)
  #  url: https://starcitizen.tools/rest.php/v1/page/Gladius
  #  method: GET
  #- name: Development wiki
  #  url: https://dev.starcitizen.tools/
  #- name: Action API (development wiki)
  #  url: https://dev.starcitizen.tools/api.php?action=query&prop=info&titles=Gladius
  #  method: GET
  #- name: REST API (development wiki)
  #  url: https://dev.starcitizen.tools/rest.php/v1/page/Gladius
  #  method: GET
 
# CI schedule
workflowSchedule:
  # Check for response time every hour
  responseTime: "0 * * * *"
  graphs: "2 * * * *"
  
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.starcitizen.tools
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  # favicon: /assets/favicon.png
  # logoUrl: /assets/sct-logo.svg
  favicon: https://starcitizen.tools/resources/assets/favicon.png
  logoUrl: https://starcitizen.tools/resources/assets/sitelogo.svg
  name: Current status - Star Citizen Wiki
  customHeadHtml: "<style>:root{--body-background-color:#131a21;--body-text-color:rgba(255, 255, 255, 0.6);--card-background-color:#282f35;--nav-background-color:transparent;--nav-border-bottom-color:transparent;--nav-current-border-bottom-color:#36c;--card-border-color:rgba(255, 255, 255, 0.05);--down-border-left-color:#dd3333;--down-background-color:#6b1020;--degraded-border-left-color:#ffcc33;--up-border-left-color:#00af89;--tag-color:#1f262c;--tag-up-background-color:#14866d;--tag-down-background-color:#b32424;--tag-degraded-background-color:#ac6600;--change-background-color:#f7b731;--error-button-border-color:#1a46ad;--error-button-background-color:#3867d6;--error-button-color:#ffffff;--submit-button-border-color:#1a46ad;--submit-button-background-color:#3867d6;--submit-button-color:#ffffff;--graph-opacity:1;--graph-filter:none}.logo>img{filter:invert(1);opacity:.3}.logo>div{display:none}</style>"
  introTitle:
  introMessage:
  navbar:
    - title: Wiki
      href: https://starcitizen.tools
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/
  theme: light
  #themeUrl: /assets/sct-dark.css

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
