# Change these first
owner: StarCitizenTools # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Wiki
    url: https://starcitizen.tools
  - name: Action API
    url: https://starcitizen.tools/api.php?action=query&prop=info&titles=Gladius
    method: GET
  #- name: REST API (main wiki)
  #  url: https://starcitizen.tools/rest.php/v1/page/Gladius
  #  method: GET
  #- name: Development wiki
  #  url: https://dev.starcitizen.tools/
  #- name: Action API (development wiki)
  #  url: https://dev.starcitizen.tools/api.php?action=query&prop=info&titles=Gladius
  #  method: GET
  #- name: REST API (development wiki)
  #  url: https://dev.starcitizen.tools/rest.php/v1/page/Gladius
  #  method: GET
 
# CI schedule
workflowSchedule:
  # Check for response time every hour
  graphs: "0 * * * *"
  responseTime: "0 * * * *"
  
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  favicon: /assets/favicon.png
  logoUrl: /assets/sct-logo.svg
  name: Current status - Star Citizen Tools
  introTitle:
  introMessage:
  navbar:
    - title: Wiki
      href: https://starcitizen.tools
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/
  theme: light
  #themeUrl: /assets/sct-dark.css

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
